# Generated by Django 4.2.23 on 2025-07-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название шаблона"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("user_application", "Уведомление пользователю о заявке"),
                            (
                                "admin_new_application",
                                "Уведомление админу о новой заявке",
                            ),
                            ("status_change", "Уведомление об изменении статуса"),
                        ],
                        max_length=30,
                        verbose_name="Тип шаблона",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=200, verbose_name="Тема письма"),
                ),
                ("html_content", models.TextField(verbose_name="HTML содержимое")),
                (
                    "text_content",
                    models.TextField(blank=True, verbose_name="Текстовое содержимое"),
                ),
            ],
            options={
                "verbose_name": "Шаблон email",
                "verbose_name_plural": "Шаблоны email",
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="Email получателя"),
                ),
                (
                    "subject",
                    models.CharField(max_length=200, verbose_name="Тема письма"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка отправки"),
                            ("delivered", "Доставлено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время отправки"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="applications.application",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.emailtemplate",
                        verbose_name="Шаблон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email уведомление",
                "verbose_name_plural": "Email уведомления",
                "ordering": ["-created_at"],
            },
        ),
    ]
