# Generated by Django 4.2.23 on 2025-07-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("osago", "ОСАГО"),
                            ("kasko", "КАСКО"),
                            ("ns", "Несчастный случай"),
                            ("klezh", "Клещ"),
                            ("mortgage", "Ипотека"),
                            ("ifl", "Имущество физических лиц"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Тип продукта",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        max_length=100, verbose_name="Отображаемое название"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание продукта")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="ProductField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=50, verbose_name="Название поля"),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Текстовое поле"),
                            ("number", "Числовое поле"),
                            ("date", "Дата"),
                            ("choice", "Выбор из списка"),
                            ("decimal", "Десятичное число"),
                        ],
                        max_length=20,
                        verbose_name="Тип поля",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, verbose_name="Обязательное поле"
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Варианты выбора"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="products.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поле продукта",
                "verbose_name_plural": "Поля продуктов",
                "ordering": ["product", "order"],
                "unique_together": {("product", "field_name")},
            },
        ),
    ]
