# Generated by Django 4.2.23 on 2025-07-24 14:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "phone",
                    models.CharField(
                        help_text="Формат: +7XXXXXXXXXX",
                        max_length=15,
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="Телефон",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Специфичные поля для каждого продукта",
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "personal_data_consent",
                    models.BooleanField(
                        default=False,
                        verbose_name="Согласие на обработку персональных данных",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий пользователя"
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий администратора"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки"
                    ),
                ),
                (
                    "user_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес пользователя"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="User Agent браузера"),
                ),
                (
                    "application_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Номер заявки",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="products.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название статуса"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Цвет в формате HEX (#FF0000)",
                        max_length=7,
                        verbose_name="Цвет для UI",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Статус, после которого заявка не может быть изменена",
                        verbose_name="Финальный статус",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус заявки",
                "verbose_name_plural": "Статусы заявок",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий к изменению"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "changed_by_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес изменившего"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="applications.application",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "new_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_status_history",
                        to="applications.applicationstatus",
                        verbose_name="Новый статус",
                    ),
                ),
                (
                    "old_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_status_history",
                        to="applications.applicationstatus",
                        verbose_name="Предыдущий статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "История статуса",
                "verbose_name_plural": "История статусов",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="applications.applicationstatus",
                verbose_name="Статус",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "created_at"], name="application_status__dc3c4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["product", "created_at"], name="application_product_02b599_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["application_number"], name="application_applica_423097_idx"
            ),
        ),
    ]
