# Generated by Django 4.2.23 on 2025-07-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "username",
                    models.CharField(max_length=100, unique=True, verbose_name="Логин"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "telegram_channel",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Telegram канал"
                    ),
                ),
                (
                    "social_networks",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON с ссылками на соцсети",
                        verbose_name="Социальные сети",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний вход"
                    ),
                ),
            ],
            options={
                "verbose_name": "Администратор",
                "verbose_name_plural": "Администраторы",
                "ordering": ["username"],
            },
        ),
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Вход в систему"),
                            ("logout", "Выход из системы"),
                            ("status_change", "Изменение статуса заявки"),
                            ("data_export", "Экспорт данных"),
                            ("profile_update", "Обновление профиля"),
                        ],
                        max_length=20,
                        verbose_name="Тип действия",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание действия")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время действия"
                    ),
                ),
                (
                    "administrator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="admin_panel.administrator",
                        verbose_name="Администратор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие администратора",
                "verbose_name_plural": "Действия администраторов",
                "ordering": ["-created_at"],
            },
        ),
    ]
